name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: pwd
    - name: test 2
      run: ls
    - name: test 3
      run: cd LiterallyOneNote
    - name: test 4
      run: pwd
    - name: test 5
      run: ls
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag literallyonenote:$(date +%s)

